name: run unit tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -B build -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build build

      - name: Run CI-safe tests
        run: |
          ctest \
            --test-dir build \
            -R ".*_unit" \
            --output-on-failure